services:
    rxu.detailedviewonline.listener:
        class: rxu\detailedviewonline\event\listener
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
